docker_image: &docker_image
  docker:
    - image: circleci/node:8.9.1

install_and_update_dependency: &install_and_update_dependency
  name: install and update dependency
  command: |
    sudo apt-get update -qq
    sudo npm install mocha -g
    npm install

deploy_firebase: &deploy_firebase
  name: deploy_firebase
  command: |
    npm run build
    sudo npm install firebase-tools -g
    firebase use ${FIREBASE_PROJECT_ID}
    firebase deploy --non-interactive --token "${FIREBASE_TOKEN}"

test: &test
  name: test
  command: |
    mocha

version: 2
jobs:
  test:
    <<: *docker_image
    steps:
      - checkout
      - run: *install_and_update_dependency
      - run: *test

  deploy:
    <<: *docker_image
        
    steps:
      - checkout
      - run: *install_and_update_dependency
      - run: *deploy_firebase

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy